bcgov/mobile-attestation-vc-controller

.dockerignore, .gitignore, src/apple.py, src/controller.py
I had some local changes that needed to go back into the main project. It re-enables Apple attestation checks.
=> fix: start adding back apple checks

.github/actions/docker-build/action.yaml, .github/workflows/main.yaml, .prettierrc, Dockerfile, README.md, devops/charts/controller/Chart.yaml, devops/charts/controller/templates/_helpers.tpl, devops/charts/controller/templates/deployment.yaml, devops/charts/controller/templates/netpol.yaml, devops/charts/controller/templates/routes.yaml, devops/charts/controller/templates/secrets.yaml, devops/charts/controller/templates/service.yaml, devops/charts/controller/values.yaml, requirements.txt, src/controller.py
Added a cicd mechanics to build a docker image and a helm chart to deploy to an OpenShift environment.
=> feat: add devops support

src/constants.py, src/controller.py
Automatically expire the nonce after a period of time.
Fixes #20
=> chore: auto expire nonce cache

fixtures/report_failure.json, src/controller.py
Useful for being able to tell in the wallet when attestation was not successful
=> feat: implement failure reporting back to the wallet

Dockerfile, devops/charts/controller/templates/netpol.yaml, devops/charts/controller/values.yaml
Copy fixtures to correct location and update image tag.
=> fix: fixture location

src/traction.py
Only load the env file in developer mode.
=> fix: traction env

devops/charts/controller/values.yaml, src/controller.py, src/traction.py
=> fix: add better logging

.devcontainer/docker-compose.yml, devops/charts/controller/templates/deployment.yaml, devops/charts/controller/templates/secrets.yaml, devops/charts/controller/values.yaml, requirements.txt, src/redis_config.py
We need to use redis as a cluster on openshift. This PR makes the necessary config changes.
=> fix: use redis cluster

devops/charts/controller/values.yaml, fixtures/offer.json
Update the credential offer template to the new schema.
=> fix: update cred offer

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, README.md, devops/charts/controller/templates/secrets.yaml, devops/charts/controller/values.yaml, fixtures/offer.json, src/apple.py, src/constants.py, src/controller.py, src/traction.py
Fill in the credential details with meaningful values and some light refactoring to simplify the controller logic. I also added a redis cluster to the devContainer so we can better match our dev environment to the deployment infra. Moved the server in the devContainer to external port `5501` because port 5000 is used on MacOS by AirDrop.
=> fix: fill in cred details

devops/charts/controller/values.yaml, src/controller.py
Use the enum value in a credential, not the value.
=> fix: use enum value

.devcontainer/docker-compose.yml, .gitignore, src/controller.py, src/goog.py, src/traction.py
changed from using basic messaging to drpc for attestation protocol
=> feat: drpc attestation

devops/charts/controller/values.yaml, scripts/cred_def.py, src/traction.py
This PR adds a script to create the cred_def based on a given schema.
=> feat: add script to create cred_def_id

README.md, src/controller.py
Add a health check I can use with kubernets.
=> feat: k8s health check

.github/workflows/main.yaml, devops/charts/controller/templates/deployment.yaml, devops/charts/controller/values_dev.yaml, devops/charts/controller/values_test.yaml
Added environment variable to deployment.
=> fix: env var

README.md, devops/charts/controller/values_prod.yaml, devops/charts/controller/values_test.yaml
Add production values and additional shortcut documentation for re-deployments.
=> fix: values for prod

src/apple.py, src/constants.py, src/goog.py, src/traction.py
Adding more logs and moving the google credentials from global scope to function scope, fetched every time so they don't expire over time. I'm hoping that's what was causing the problems after a day or so.
=> fix: add more logs and fetch fresh google creds each attestation

devops/charts/controller/values_dev.yaml, devops/charts/controller/values_prod.yaml, devops/charts/controller/values_test.yaml
Update image version to one that contains recent fixes.
=> chore: update image version

devops/charts/controller/values_prod.yaml
Correct the production traction URL.
=> fix: traction prod url

fixtures/request_attest_verif.json, scripts/send_proof.py, src/traction.py
This is a script to generate a test proof from the command line since in prod Traction we cannot create them through the web UI.
=> chore: script to generate a test proof

devops/charts/controller/values_dev.yaml, devops/charts/controller/values_test.yaml
Update the image tags for dev and test for deployment.
=> chore: update dev and test img tag

devops/charts/controller/values_prod.yaml
Updated the prod image tag to for deployment in our **new** namespace only.
=> feat: update prod image tag to 0a464e8

src/controller.py
Fix extraction of apple attestation v2 key_id.
=> fix: apple v2 attestation key

devops/charts/controller/values_dev.yaml, devops/charts/controller/values_prod.yaml, devops/charts/controller/values_test.yaml, devops/charts/redis/README.md
Update to the latest docker image build.
=> chore: update image tag
